E-Commerce Website/Controllers/AuthorsController.cs
using E_Commerce_Website.Data;
using E_Commerce_Website.Data.Services;
using E_Commerce_Website.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace E_Commerce_Website.Controllers
{

    public class AuthorsController : Controller
    {
        private readonly IAuthorsService _service;

        public AuthorsController(IAuthorsService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {

            var data = await _service.GetAllAsync();
            return View(data);
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName, ProfilePictureURL, Bio")]Author author)
        {
            if(!ModelState.IsValid)
            {
                return View(author);
            }
            await _service.AddAsync(author);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int id)
        {
            var authorDetails = await _service.GetByIdAsync(id);

            if (authorDetails == null) return View("NotFound");
            return View(authorDetails);
        }

        public async Task<IActionResult>Edit(int id)
        {
            var authorDetails = await _service.GetByIdAsync(id);

            if (authorDetails == null) return View("NotFound");
            
            return View(authorDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id, FullName, ProfilePictureURL, Bio")] Author author)
        {
            if (!ModelState.IsValid)
            {
                return View(author);
            }
            await _service.UpdateAsync(id, author);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var authorDetails = await _service.GetByIdAsync(id);

            if (authorDetails == null) return View("NotFound");

            return View(authorDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var authorDetails = await _service.GetByIdAsync(id);
            if (authorDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

E-Commerce Website/Controllers/OrdersController.cs
using E_Commerce_Website.Data.Cart;
using E_Commerce_Website.Data.Services;
using E_Commerce_Website.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace E_Commerce_Website.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IPianoCoursesService _coursesService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;
        public OrdersController(IPianoCoursesService coursesService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _coursesService = coursesService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }
        public async Task<IActionResult> Index()
        {
            string userId = "";
            var orders = await _ordersService.GetOrdersbyUserIdAsync(userId);
            return View(orders);
        }


        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;
            var response = new ShoppingCartViewModel()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _coursesService.GetPianoCourseByIdAsync(id);

            if(item != null)
            {
                _shoppingCart.AddItemtoCart(item);

               
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _coursesService.GetPianoCourseByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);


            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = "";
            string userEmailAddress = "";

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);

            await _shoppingCart.ClearShoppingCartAsync();
            return View("OrderCompleted");
        }
    }
}

E-Commerce Website/Controllers/PianoCoursesController.cs
using E_Commerce_Website.Data;
using E_Commerce_Website.Data.Services;
using E_Commerce_Website.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace E_Commerce_Website.Controllers
{
    public class PianoCoursesController : Controller
    {
        private readonly IPianoCoursesService _service;

        public PianoCoursesController(IPianoCoursesService service)
        {
            _service = service;
        }
        
        public async Task<IActionResult> Index()
        {
            var allPianoCourses = await _service.GetAllAsync();
            return View(allPianoCourses);
        }

        public async Task<IActionResult> Filter(string searchString)
        {
            var allPianoCourses = await _service.GetAllAsync();

            if(!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = allPianoCourses.Where(n => n.Name.Contains(searchString) || n.Description.Contains(searchString)).ToList();
                return View("Index", filteredResult);
            }
            return View("Index", allPianoCourses);
            
        }



        public async Task<IActionResult> Details (int id)
        {
            var pianoCourseDetail = await _service.GetPianoCourseByIdAsync(id);
            return View(pianoCourseDetail);
        }

        public async Task<IActionResult> Create()
        {
            var pianoCourseDropDownData = await _service.GetNewPianoCourseDropDownValues();

            ViewBag.Authors = new SelectList(pianoCourseDropDownData.Authors, "Id", "FullName");
            
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(newPianoCourseVM course)
        {
            if (!ModelState.IsValid)
            {
                var pianoCourseDropDownData = await _service.GetNewPianoCourseDropDownValues();
                ViewBag.Authors = new SelectList(pianoCourseDropDownData.Authors, "Id", "FullName");
                return View(course);
            }

            await _service.AddNewPianoCourseAsync(course);
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Edit(int id)
        {

            var pianoCourseDetails = await _service.GetPianoCourseByIdAsync(id);
            if (pianoCourseDetails == null) return View("NotFound");


            var response = new newPianoCourseVM()
            {
                Id = pianoCourseDetails.Id,
                Name = pianoCourseDetails.Name,
                Description = pianoCourseDetails.Description,
                Price = pianoCourseDetails.Price,
                Level = pianoCourseDetails.Level,
                ImageURL = pianoCourseDetails.ImageURL,
                CourseCategory = pianoCourseDetails.CourseCategory,
                AuthorIds = pianoCourseDetails.Authors_Courses.Select(n => n.AuthorId).ToList(),
            };

            var pianoCourseDropDownData = await _service.GetNewPianoCourseDropDownValues();

            ViewBag.Authors = new SelectList(pianoCourseDropDownData.Authors, "Id", "FullName");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, newPianoCourseVM course)
        {


            if (id != course.Id) return View("NotFound");

            if (!ModelState.IsValid)
            {
                var pianoCourseDropDownData = await _service.GetNewPianoCourseDropDownValues();
                ViewBag.Authors = new SelectList(pianoCourseDropDownData.Authors, "Id", "FullName");
                return View(course);
            }

            await _service.UpdatePianoCourseAsync(course);
            return RedirectToAction(nameof(Index));
        }
    }
}

E-Commerce Website/Views/Shared/NotFound.cshtml
<div class="row text-center">
    <div class="col-md-6 offset-3">
        <h1 class="text-info">This Actor doesn't exist in our database</h1>

    </div>
    <div class="row text-center">
        <a class="btn btn-outline-success" asp-controller="PianoCourses" asp-action="Index">Go Back to Home Page</a>

    </div>
</div>

E-Commerce Website/Views/Shared/_Identity.cshtml
@inject UserManager<ApplicationUser> UserManager;

@if (!User.Identity.IsAuthenticated)
{
    <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="Login">
        <i class="bi bi-box-arrow-in-right"></i> Log in
    </a>
    <span style="padding: 5px;"></span>

    <a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register">
        <i class="bi bi-person-plus"></i> Register
    </a>
}
else
{

    @*User profile section*@
    <div class="dropdown">
        <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn" data-toggle="dropdown"
                aria-expanded="false">
            <i class="bi bi-person-badge"></i> Hello @UserManager.GetUserName(User)
        </button>
        <ul class="dropdown-menu" aria-labelledby="profile-btn">
            <li>
                <a class="dropdown-item" asp-controller="Orders" asp-action="Index">
                    <i class="bi bi-list"></i> Orders
                </a>
            </li>
        </ul>
    </div>
    <span style="padding: 5px;"></span>
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"></i> Log out
        </button>
    </form>
}

E-Commerce Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - E_Commerce_Website</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
</head>
<body>
    
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="PianoCourses" asp-action="Index">Musicursum</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PianoCourses" asp-action="Index"><i class="bi bi-film"></i> Courses</a>
                        </li>

                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {   <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear"></i> Management
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                                    <a class="dropdown-item" asp-controller="Authors" asp-action="Index"><i class="bi bi-person-square"></i>Authors</a>
                                </div>
                            </li>
                        }




                            @*<li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </li>*@
                            @*<li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="PianoCourses" asp-action="Index">Courses</a>
            </li>*@
                    </ul>

                    <form class="form-inline my-2 my-lg-0" asp-controller="PianoCourses" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a course..." aria-label="Recipient's username" aria-describedby="button-addon2">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>

                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>


                 

                    <partial name="_Identity.cshtml"/>

                    @*<a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="Login">
                        <i class="bi bi-box-arrow-in-right"></i> Log in
                    </a>

                    <a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register">
                        <i class="bi bi-person-plus"></i> Register
                    </a>





                    <div class="dropdown">
                        <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn" data-toggle="dropdown"
                                aria-expanded="false">
                            <i class="bi bi-person-badge"></i> Hello User
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="profile-btn">
                            <li>
                                <a class="dropdown-item" asp-controller="Orders" asp-action="Index">
                                    <i class="bi bi-list"></i> Orders
                                </a>
                            </li>
                        </ul>
                    </div>

                    <span style="padding: 5px;"></span>
                    <form asp-controller="Account" asp-action="Logout">
                        <button class="btn btn-outline-danger my-2 my-sm-0">
                            <i class="bi bi-box-arrow-in-right"></i> Log out
                        </button>
                    </form>*@

                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - E_Commerce_Website
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

E-Commerce Website/Views/Shared/_PartialViewCreateItem.cshtml
@model string;


@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <div style="position: fixed; right: 15px; top: 73px" class="text-white">
        <a class="btn btn-success" asp-controller="@Model" asp-action="Create"><i class="bi bi-plus-circle"></i>Add new </a>

    </div>
}